---
branch: master
tagFormat: "v${version}"
plugins:
  - "@crud-studio/semantic-release-maven"
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/git"
  - "@semantic-release/github"
